### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by CodyPChristian** [sublimehq/anim_encoder#13]
Hello,

I get a Traceback error when trying to use the script on Ubuntu Vagrant.

vagrant@vagrant-ubuntu-trusty-64:~/anim_encoder$ ./anim_encoder.py computer_typing
libdc1394 error: Failed to initialize libdc1394
Traceback (most recent call last):
  File "./anim_encoder.py", line 234, in <module>
    generate_animation(sys.argv[1])
  File "./anim_encoder.py", line 141, in generate_animation
    zero = images[0] - images[0]
IndexError: list index out of range

**Comment by l-hendriks** [comment]
Change anim_encoder.py line 132 to your filenames.

Just had the same error.

**Comment by CodyPChristian** [comment]
Example of what you changed it to?

**Comment by l-hendriks** [comment]
The filenames of your files.

**Comment by CodyPChristian** [comment]
Tried that, still not working FYI.

**Comment by fuermosi777** [comment]
Change all your png files' name to something like "screen_1000.png" (replace numbers)
