### ISSUE TITLE
about max pictures

### ISSUE THREAD

**Issue by hugcoday** [sublimehq/anim_encoder#21]
I have 178 pictures , I run this  ,it error.

` sudo python anim_encoder.py frames
frames packing, num rects: 27 num frames: 20
Traceback (most recent call last):
  File "anim_encoder.py", line 234, in <module>
    generate_animation(sys.argv[1])
  File "anim_encoder.py", line 189, in generate_animation
    dy, dx = allocator.allocate(w, h)
  File "anim_encoder.py", line 111, in allocate
    raise RuntimeError()
RuntimeError`

I run example ,it's success

**Comment by wbond** [comment]
This is a duplicate of #11. See https://github.com/sublimehq/anim_encoder/issues/11#issuecomment-316561807 for details about what is going on.
